
exports.seed = function(knex, Promise) {
  return knex.raw('DELETE FROM "progress"; ALTER SEQUENCE progress_id_seq RESTART WITH 21')
    .then(function () {
      const progressions = [{
        id: 1,
        user_id: 1,
        language: 'French',
        mode: 'Training',
        game_number: 1,
        percentage_correct: 23
      }, {
        id: 2,
        user_id: 1,
        language: 'French',
        mode: 'Training',
        game_number: 2,
        percentage_correct: 31
      }, {
        id: 3,
        user_id: 1,
        language: 'French',
        mode: 'Training',
        game_number: 3,
        percentage_correct: 40
      }, {
        id: 4,
        user_id: 1,
        language: 'French',
        mode: 'Training',
        game_number: 4,
        percentage_correct: 48
      }, {
        id: 5,
        user_id: 1,
        language: 'French',
        mode: 'Training',
        game_number: 5,
        percentage_correct: 44
      }, {
        id: 6,
        user_id: 1,
        language: 'French',
        mode: 'Training',
        game_number: 6,
        percentage_correct: 53
      }, {
        id: 7,
        user_id: 1,
        language: 'French',
        mode: 'Training',
        game_number: 7,
        percentage_correct: 60
      }, {
        id: 8,
        user_id: 1,
        language: 'French',
        mode: 'Training',
        game_number: 8,
        percentage_correct: 74
      }, {
        id: 9,
        user_id: 1,
        language: 'French',
        mode: 'Training',
        game_number: 9,
        percentage_correct: 77
      }, {
        id: 10,
        user_id: 1,
        language: 'French',
        mode: 'Training',
        game_number: 10,
        percentage_correct: 91
      }, {
        id: 11,
        user_id: 3,
        language: 'French',
        mode: 'Single',
        game_number: 1,
        percentage_correct: 40
      }, {
        id: 12,
        user_id: 3,
        language: 'French',
        mode: 'Single',
        game_number: 2,
        percentage_correct: 22
      }, {
        id: 13,
        user_id: 3,
        language: 'French',
        mode: 'Single',
        game_number: 3,
        percentage_correct: 88
      }, {
        id: 14,
        user_id: 3,
        language: 'French',
        mode: 'Single',
        game_number: 4,
        percentage_correct: 6
      }, {
        id: 15,
        user_id: 3,
        language: 'French',
        mode: 'Single',
        game_number: 5,
        percentage_correct: 17
      }, {
        id: 16,
        user_id: 3,
        language: 'French',
        mode: 'Single',
        game_number: 6,
        percentage_correct: 97
      }, {
        id: 17,
        user_id: 3,
        language: 'French',
        mode: 'Single',
        game_number: 7,
        percentage_correct: 41
      }, {
        id: 18,
        user_id: 3,
        language: 'French',
        mode: 'Single',
        game_number: 8,
        percentage_correct: 14
      }, {
        id: 19,
        user_id: 3,
        language: 'French',
        mode: 'Single',
        game_number: 9,
        percentage_correct: 38
      }, {
        id: 20,
        user_id: 3,
        language: 'French',
        mode: 'Single',
        game_number: 10,
        percentage_correct: 80
      }];
      return knex('progress').insert(progressions);
    });
};
